### ISSUE TITLE
Your plugin break material_select

### ISSUE THREAD

**Issue by freddy-daniel** [guillaumepotier/Parsley.js#1192] opened 2017-04-18 12:55 UTC
HI I'm using Materializecss for my project and integrated parsley validation in it 
Everything working file no problem in validation. But after parsley validation run if we call $('select').material_select() . Select label is coincide with option .Screenshot attached here.

calling material_select() before parsley validation

![capture1](https://cloud.githubusercontent.com/assets/19286267/25131621/0194b85e-2464-11e7-80be-6f9105e39779.JPG)

calling material_select() after parsley validation

![capture2](https://cloud.githubusercontent.com/assets/19286267/25131622/0195bac4-2464-11e7-8c69-8a90a7e176dc.JPG)

**Comment by marcandre** [comment] 2017-04-18 14:17
I'm sorry you are having issues.
I'm also sorry that you didn't read that without a minimal running example we can not investigate further.
Closing until then.

**Closed by marcandre** 2017-04-18 14:17 UTC

**Comment by fega** [comment] 2017-04-18 14:21
Did you need to be so aggressive?

**Comment by marcandre** [comment] 2017-04-18 14:34
I'm sorry you read my message as aggressive.

Here is a more detailed message.

My name is Marc-André and **I'd like to help**. I'm not the original author but I liked the project so much I started contributing more and more. Now I'm the (only) maintainer.

#### How you can help

I'd like **you to help me** by doing everything you can on your end so I have to do less on my end. As you can imagine, I have already spent a lot of time making this project better, and given the price you're paying to use it or the efforts you have made contributing to this project, I think it's fair to ask that.

To serve that goal, I wrote that bug reports should **provide a working example** in the [READ ME](https://github.com/noelboss/featherlight#reporting-bugs-and-issues) file. Still, some people don't provide a working example here.

I requested the same in the [Contributing Guidelines](https://github.com/noelboss/featherlight/blob/master/.github/CONTRIBUTING.md). Even though GitHub has a paragraph saying "Please review the guidelines for contributing to this repository." that shows up whenever someone creates an issue, some people don't provide a working example.

Finally, GitHub allowed us to write a template issue, in which I wrote
> you must provide a minimal example in a CodePen
> starting from http://jsfiddle.net/JNsu6/15/.

Still, some people like you delete this text and report a bug without a working example. So I am wondering: **why did you feel it was the right thing to do**? What could I possibly have done so that this basic wish was respected? I must admit that I feel disrespected whenever someone completely ignores my requests. I understand that most developers don't feel the urge to help by digging in, inspecting the code and contributing back with great bug reports or pull requests, but it saddens me when people show little care and disregard maintainer wishes.

It would help me a lot if you helped me find a solution so that bug reports are posted with working examples.

#### Why Working Examples?

A working example is a great opportunity to minimize the problem, have the least amount of dependencies, etc.

Maybe by doing this, you will figure out what is going on. Or maybe the issue is something else than what you thought it was.

Or maybe the issue exists and this way, I can see it with a few clicks. If I only get partial code, I need to guess what the issue could be. Sometimes my understanding of the code is enough, I'll think about it and "ha ha", I know what the issue is. Usually I don't though, so then I have to copy-paste the bits and pieces given to me and try to reproduce the issue. This takes *me* some time that *you* could have spent.

So, if you have hints on how to avoid bug reports without working example, please let me know.

More to the point, provide a working example, for this project or any other where you can. I'm closing this and will reopen when there is a working example. Thank you for your understanding.

**Comment by marcandre** [comment] 2017-04-18 14:38
PS: It may just be because Parsley adds a `div` to put errors in and that `div` confuses the other library. There's an option to specify the error div which might alleviate this, or some tweaks to Materializecss so it's CSS is more robust.

**Comment by freddy-daniel** [comment] 2017-04-21 05:59
Thanks guys, i fixed it by using below css
`.select-wrapper+ul.parsley-errors-list+label`
`{`
    `	position: absolute;`
    `    top: -14px;`
    `    font-size: .8rem;`
`}`
