### ISSUE TITLE
Remove sourcemaps from distribution files.

### ISSUE THREAD

**Issue by dahliacreative** [guillaumepotier/Parsley.js#1108] opened 2016-05-20 11:13 UTC
What kind of issue is this? (put 'x' between the square brackets)
- [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
     something, or to understand why something isn't working the way you expect it to, use
     http://stackoverflow.com/questions/ask .
     Provide working code, starting from http://codepen.io/marcandre/pen/jqbzyN?editors=101.
     We monitor the tag `parsley.js`.
- [ ] Bug report. If you’ve found a bug, you must provide a minimal example in a CodePen,
     starting from http://codepen.io/marcandre/pen/jqbzyN?editors=101 .
- [x] Feature Request. Make sure there's no good way to do what you want first;
     consider asking on http://stackoverflow.com/questions/ask first.

Hi, so I use bower, and bower installer to install dependencies, when requesting distribution files I don't require the sourcemap, however because the sourcemap is not included in the bower file as a main file it doesn't get installed by bower installer causing my grunt tasks to fail due to the missing sourcemap.

Can you either exclude sourcemaps from distribution files, or include the sourcemap in bower.json as a main file? Preferably the former as I have no requirement for source maps in production code.

Thanks! :)

**Comment by marcandre** [comment] 2016-05-31 03:06
Sorry for the delay, I was travelling abroad.
I'm not too sure of the consequences of what you are requesting (nor of what your issue is, i.e. why does grunt fail).
It looks like popular projects (e.g. [underscore](https://github.com/jashkenas/underscore/blob/master/bower.json), [es5-shim](https://github.com/es-shims/es5-shim/blob/master/bower.json)) do not include the `.map` file in their bower.json either...

**Comment by dahliacreative** [comment] 2016-05-31 08:33
Hi, so basically, using bower-installer installs the main file listed in bower, but does not include the map file. However as the main file has the link to the source map in it, grunt fails because it cannot find the map file (as bower installer did not find it).

As your distribution code is compiled, I don't think there is any need for it to reference a map file. Map files should only really be for development of the plugin.

**Comment by dahliacreative** [comment] 2016-05-31 08:36
https://github.com/jashkenas/underscore/blob/master/underscore.js, https://github.com/es-shims/es5-shim/blob/master/es5-shim.js they also don't include links to map files in their dist code.

**Comment by marcandre** [comment] 2016-05-31 12:02
My bad, wrong examples, these have a `.map` file but only for the minimized file. Most libs don't get compiled like we do, I guess.
I'll include the `.map` in the main files and created https://github.com/babel/generator-babel-boilerplate/issues/358

**Comment by marcandre** [comment] 2016-05-31 12:51
Mmm, `npm publish` gives me `npm ERR! registry error parsing json`.

I'm reverting this for now.

**Comment by dahliacreative** [comment] 2016-05-31 12:56
I think in the unminified version best to just take out the source map all together, it's really not needed :/

**Comment by marcandre** [comment] 2016-05-31 13:05
I have to think on it. The actual source is ES6 and we'll be using more and more of those features, so the even the unminified version can really use a sourcemap...

**Comment by jmeas** [comment] 2016-05-31 15:31
Which Grunt plugin is failing? Do other plugins work?

**Comment by marcandre** [comment] 2016-05-31 16:20
FWIW, the error I had with `npm publish` might not be related, I can't push even without the change...

```
Unexpected token < in JSON at position 1
npm ERR! 
npm ERR! <?xml version="1.0" encoding="utf-8"?>
npm ERR! <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
npm ERR!  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
npm ERR! <html>
npm ERR!   <head>
npm ERR!     <title>503 backend write error</title>
npm ERR!   </head>
npm ERR!   <body>
npm ERR!     <h1>Error 503 backend write error</h1>
npm ERR!     <p>backend write error</p>
npm ERR!     <h3>Guru Mediation:</h3>
npm ERR!     <p>Details: cache-ord1726-ORD 1464700602 3125273478</p>
npm ERR!     <hr>
npm ERR!     <p>Varnish cache server</p>
npm ERR!   </body>
npm ERR! </html>
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mal/parsley/npm-debug.log
```

**Comment by jmeas** [comment] 2016-05-31 16:36
@marcandre can you post a link to the file?

**Comment by marcandre** [comment] 2016-05-31 17:02
Yeah, the one in master. I tried `npm publish` on 5869143c36708f5 and that failed.

**Comment by dahliacreative** [comment] 2016-06-03 14:02
> I have to think on it. The actual source is ES6 and we'll be using more and more of those features, so the even the unminified version can really use a sourcemap...

Yep, I get that, but people who are installer parsley via bower for their projects aren't interested in the source of the plugin, they aren't developing the plugin they are simply using it, so they have no need to see what parts of the plugin relate to the source.

I hope that makes sense? Sourcemaps are only valuable to you guys who develop the plugin, not the people that use it. Not sure how else to explain.

Thanks for looking into it though!

**Comment by dahliacreative** [comment] 2016-06-03 14:05
> Which Grunt plugin is failing? Do other plugins work? What's the error message? Before we go releasing new versions of Parsley, let's get some more information...

I'm not really asking for a new release, there isn't an issue with the plugin, it' simply the inclusion of a link to a sourcemap without the sourcemap being available causes concatenation and uglification tasks in grunt to fail.

And seeing as, as a user of parsley, I have no need for the sourcemaps as I'm not interested in the source, it seems a good idea to just remove them from the distribution files.

I would recommend have two build tasks, one for development which includes the sourcemaps, and one for distribution which doesn't.

**Comment by jmeas** [comment] 2016-06-03 17:45
> ...they aren't developing the plugin they are simply using it, so they have no need to see what parts of the plugin relate to the source.

I don't think that this is strictly true. If everything works as it should, then you're exactly right. But if a consumer encounters a bug in Parsley (very possible!), I think they'd rather see a useful stack trace than hard-to-read minifiied source.

For that reason, I think there's value in always including a source map – for both transpiled and minified distribution files. However, I came to realize that maps for the transpiled source only might not be that useful. There are two requirements for them to be useful:

1. the library must ship the source files when distributing
2. the user must allow their browser to serve the source files

Although not every library ships the source files, Parsley does when installed over npm, so that's fine. It's the second point that causes problems, I think. Most folks won't set up their server to serve files from `node_modules`, so that map is likely useless. I'm going to update the boilerplate that this project uses to not ship that source map.

Although this should solve your problem, I still think some plugin you're using (`bower-installer`, maybe?) still has an issue with handling source maps in a robust way.

**Comment by marcandre** [comment] 2016-06-03 22:02
> And seeing as, as a user of parsley, I have no need for the sourcemaps as I'm not interested in the source, it seems a good idea to just remove them from the distribution files.

It saddens me that many developers feel the same way you do. I wish more users felt that they could be part of a project, that they could contribute to it, and that as users, they were part of the project.

In any case, I feel the sourcemap is part of the source and will try again to add it to the main files.

**Comment by jmeas** [comment] 2016-06-03 22:11
@marcandre you may know this, but there are ways to tell webpack to inline the map as a comment in the source file rather than externalizing it.

Pros:

- It solves this issue

Cons:

- If a user doesn't minify parsley, or uses it from a CDN, they always download the source map

Personally, I don't think it's worth that con, but I'll leave that up to you :v:

**Comment by marcandre** [comment] 2016-06-03 22:23
Right, indeed, I much prefer sourcemap separated. Otherwise the minified source + inline source map would be slightly better I guess.

**Comment by dahliacreative** [comment] 2016-06-12 12:35
> It saddens me that many developers feel the same way you do. I wish more users felt that they could be part of a project, that they could contribute to it, and that as users, they were part of the project.

This isn't really about being part of the project, the is purely from the point of view of using the plugin in my projects. When I use it in my projects I don't need the source map.

If I found a bug when using the plugin then I would debug it and open up an issue or if I had time a PR.

This is purely about the fact that I use parsley on pretty much every project and when I put my project live I don't need sourcemaps!

**Comment by dahliacreative** [comment] 2016-06-12 12:39
> Although this should solve your problem, I still think some plugin you're using (bower-installer, maybe?) still has an issue with handling source maps in a robust way.

It's nothing to dow with bower installer or grunt.
Well it kind of is to do with bower installer, the point of bower installer is to just copy over the main files listed in the bower.json, so because the source map isn't included it doesn't get copied over, but the js file listed has a link to the sourcemap, which then causes grunt to fail because it doesn't exist.

It's not really a major issue, just if it isn't changed, my automation process goes from being 100% automated to me having to remove the link from the js file, then all my team when they work on the project have to do the same, which then leads to inefficiencies in our workflow.

I think either exclude the source map from the dist files, or include them in the bower.json, either way I'm not really fussed.

**Comment by jmeas** [comment] 2016-06-17 18:40
Opened an issue on `bower-installer` (https://github.com/blittle/bower-installer/issues/154), which is the cause of this issue, I think.

@megawac informed me that maps are useful even w.o. source files, so I don't think any change needs to happen here. Gonna test that out myself to verify, but he sounds pretty confident.

----

@dahliacreative I don't think it's going to work out for you to cross your fingers and hope that the files you're pulling in don't have source maps. A ton of new libraries are being transpiled these days – I'd expect most things I use to have their own maps, even for the non-minified versions.

tbqh I'd probably just stop using `bower-installer` – seems like unnecessary toolchain bloat that's just causing problems :P

**Comment by dahliacreative** [comment] 2016-06-23 09:41
I don't see why you can just include the source maps in the main manifest for bower.json. this would solve everything as bower-installer would then copy them over.

I'f I can't use bower installer then I would have to manually include all my 3rd party libraries instead of using grunt to automate the process.

**Comment by dahliacreative** [comment] 2016-07-02 20:04
I don't know why I didn't think of it earlier, but you can override the bower settings for plugins with bower-installer. So I've managed to get it sorted.

**Comment by marcandre** [comment] 2016-07-02 22:44
Cool, glad to hear this. So should we close this?

**Closed** 2016-11-08 16:18 UTC
