### ISSUE TITLE
Remote parsley should have option to disable caching

### ISSUE THREAD

**Issue by jbojcic1** [guillaumepotier/Parsley.js#813] opened 2015-01-02 19:15 UTC
Currently parsley remote caches every response and that can be a problem. For example I am working on a single page app and when creating user I am checking is email unique so this happens:
1. I normally create user with email which wasn't used earlier (parsley response is cached)
2. I try to create user with same email again and since response is cached it passes validation again

**Comment by marcandre** [comment] 2015-01-29 20:44
Probably the best solution is for the cache to be owned by the *form* instead of the *validator*. This would resolve your issue, right?

**Comment by guillaumepotier** [comment] 2015-01-29 20:51
Hi @jbojcic1,

I'm using parsley remote @Wisembly for the same purpose and it works well! Like @marcandre said this is not Parsley role to call api to create objects, since it only send (normally) only the input value, not the whole form.

Moreover, the parsley remote url should make a `GET` call while the form make a `POST` one to create the email in your database.

In parsley point of view (following REST principle) every unique url call should always return same response and do the same action. That's why we cache every request that is made to avoid too much stress on servers especially for existence checking like you do in your case.

I might add a parsley remote example in documentation, this your use case is quite typical and should not confuse users.

Best

**Comment by marcandre** [comment] 2015-01-29 21:40
I presume that @jbojcic1 is using ajax to `POST` the user creation, so the parsley lib is never reloaded, while @guillaumepotier probably uses the default form submission which reloads the whole page?

> every unique url call should always return same response and do the same action

Well, no and yes. A `GET` should be *idempotent*, i.e. not have side effects server-side. The response can be different every time though. Otherwise we'd be reading the same news everyday :smile:

I think we should probably invalidate caches just before form submission (onSubmitValidate, and in the remote case just before we re-submit the form). @guillaumepotier can you think of a case when that's would create issues?

**Comment by guillaumepotier** [comment] 2015-01-29 22:30
We have to make sure it solves @jbojcic1 case but no that seems a pretty good idea yes.

**Comment by jbojcic1** [comment] 2015-01-30 12:26
Yes, like @marcandre said, I use POST to create user not form submission.

**Comment by jbojcic1** [comment] 2015-01-30 12:46
@guillaumepotier @marcandre 
I never submit my form in a

**Comment by guillaumepotier** [comment] 2015-01-30 12:58
Like @marcandre said

> I think we should probably invalidate caches just before form submission (onSubmitValidate, and in the remote case just before we re-submit the form). @guillaumepotier can you think of a case when that's would create issues?

we might even clear cache automatically after a validation success, what do you think, would it solve your problem?

**Comment by jbojcic1** [comment] 2015-01-30 13:34
Yes it would. Clearing on a success is the best option for me but it can cause unnecessary requests for remote validation when server response doesn't change like for emails. So in my opinion it would probably be the best to have parameter to chose whether to clear cache on success or not.

**Comment by marcandre** [comment] 2015-02-02 15:01
Cache now clears on submit. Merged in `master`.

Thanks for reporting this issue @jbojcic1 !

**Closed by marcandre** 2015-02-02 15:01 UTC
Labels: bug

**Comment by bdairy** [comment] 2015-02-18 16:56
Everything guys you did solves my problem... I am new to this and I don't know how to use this in my code... any help please??? can any one give me a step by step walkthrough on how I can clear the cache after validation???

I am using asycvalidator  in my controller as follows : 

  window.ParsleyExtend = {
        asyncValidators: {
            checkusername: {
                fn: function (xhr) {
                    //console.log($('[name="userName"]'));
                    return 404 === xhr.status;

                },
                url: authService.serviceBase + 'api/account/CheckUserName/'// + $('[name="userName"]').text()
            },
            checkusernameforupdate: {
                fn: function (xhr) {
                    return 404 === xhr.status;
                },
                url: authService.serviceBase + 'api/account/CheckUserNameForUpdate/' + $scope.urlUserName
            },
            checkemail: {
                fn: function (xhr) {
                    return 404 === xhr.status;
                },
                url: authService.serviceBase + 'api/account/CheckEmail/'
            },
            checkemailforupdate: {
                fn: function (xhr) {
                    return 404 === xhr.status;
                },
                url: authService.serviceBase + 'api/account/CheckEmailForUpdate/' + $scope.urlUserName
            }
        }
    };

**Comment by marcandre** [comment] 2015-02-18 17:05
@bdairy There's nothing special to do, you just need to use the version with that fix. I don't think it has been released yet though, so download `master` and `grunt build` to use it...

**Comment by bdairy** [comment] 2015-02-19 12:15
Sorry for the inconvenience,., just to be clear,, I have to download the files in this this link (https://github.com/guillaumepotier/Parsley.js)   and replace my Parsley folder in the solution??? Again I am totally new to this and your help is appreciated..

**Comment by marcandre** [comment] 2015-02-19 12:32
@bdairy: I made a release candidate for you: [use this build](https://github.com/guillaumepotier/Parsley.js/releases/tag/2.1.0-rc2)

Download and use the files you need in the `dist/` folder.

**Comment by bdairy** [comment] 2015-02-19 12:41
Thanks,, I did replace the files,, parsley is working fine but it is still caching the request...what should I do to stop that??

**Comment by marcandre** [comment] 2015-02-19 12:48
Use your browser's developer tools and check if the request is sent only once or multiple times. It's possible your browser is caching the response, in which you need to either fix your server's response or specify an ajax option `remoteOption: {cache: false}`.

**Comment by bdairy** [comment] 2015-02-19 13:12
in the network tab the request is sent only once,, I am using angular js in my application and in the app run I have an interceptor that has ajax setup functionality to add an authorization header,.,, there I also added the remoteOption: {cache: false} to be like this:

 if (authData) {
            $.ajaxSetup({
                remoteOption: {cache: false},
                headers: { 'Authorization': 'Bearer ' + authData.token }
            });
            config.headers.Authorization = 'Bearer ' + authData.token;
          }

Now I can see in the headers that there are no cahing... but still the request is cahced!! 
![image](https://cloud.githubusercontent.com/assets/10797121/6267075/5fd44088-b85a-11e4-90ee-63bdaceaa548.png)

I am also using AngularJS UI-Router instead of njRoute for navigation... I think this one is also caching my pages...

**Comment by marcandre** [comment] 2015-02-19 13:20
You can double check that the parsley code works as expected. Load your page, enter invalid data, hit submit. At that point, `$('form').parsley._remoteCache` should have stuff in it.
Enter valid data (and complete the form so it's all valid), submit. At that point, `$('form').parsley._remoteCache` should be empty.

If it is, I'm afraid you'll have to investigate further what's going on with the rest of your code and libraries.

If it isn't, then I'd need some sort of demo (fiddle or URL) to see it to believe it...

**Comment by bdairy** [comment] 2015-02-19 13:28
Just one question... the clear cache functionality only occurs on form submitting?  because in my case the caching occurs before that.. it is a remote validator that check if the value is valid on focus out of my field.. only... what  I understand from you that this only happens when the form submits.. is that right??

**Comment by marcandre** [comment] 2015-02-19 13:41
> what I understand from you that this only happens when the form submits is that right??

Yeah, that's right, as I wrote in my commit message, in the Changelog entry, in my comments in this thread, etc.

Is it possible to know what actual *problem* you're having?

**Comment by jbojcic1** [comment] 2015-02-19 13:43
I haven't try this yet so I'll try now to see if it clears cache to me. @marcandre do I need to include both parsley.remote.min.js and parsley.min.js or just parsley.remote.min.js is enough, because currently i have only one file - parsley_remote.min.js?

**Comment by marcandre** [comment] 2015-02-19 14:03
@jbojcic1 pick one or the other (in your case should be the remote one as you are using asynch requests)

**Comment by jbojcic1** [comment] 2015-02-19 14:11
@marcandre so parsley.remote.min.js is parsley.min.js + async requests? Also I tried and it's still caching. Maybe because I am not submitting form?
I do it like this:

parsleyForm = $('#userPanel').parsley({
        errorsWrapper: ...,
        errorTemplate: ...,
        errorsContainer: ...,
        classHandler: ...
    });

parsleyForm.asyncValidate().done(function () {
});

**Comment by bdairy** [comment] 2015-02-19 14:14
My exact problem is that I am using a remote validator on this field..

 <input type="text" name="userName" class="form-control" data-ng-model="user.userName" value=""
                                 data-parsley-remote
                                 data-parsley-remote-validator='checkusernameforupdate'
                                 data-parsley-trigger="focusout"
                                 data-parsley-remote-message="User name is already registerd in the system"
                                 required="required" />

when I check the username for example user1... the remote validator is called upon the focusout method of the field.. it checks if user1 exists or not...

then if I changed it to user2.. the validator if fired again on the focusout event..

now if I go back to check user1.. the validator is not working.. unless I use another value like user3

even if I naviagate away from the page then came back,, Unless i hit Ctrl+F5 the validator will still cache all the requests..

**Comment by marcandre** [comment] 2015-02-19 14:21
> now if I go back to check user1.. the validator is not working.. 

You mean the ajax request is not re-sent. This is by design. That's the cache working.

@bdairy, I will not respond any further your inquiries.

**Comment by marcandre** [comment] 2015-02-19 14:28
> so parsley.remote.min.js is parsley.min.js + async requests?

Exactly

> Also I tried and it's still caching. Maybe because I am not submitting form?

Indeed.

You should use bind your user creation code with `on('submit')` on your form, *after* parsley.

**Comment by jbojcic1** [comment] 2015-02-19 14:52
@marcandre
As I already said earlier: "I never submit my form in a classical way. It's a single page app so there is no page reload." When you submit form whole page is reloaded so this doesn't work for me. Also if I am not wrong, previously cache was always cleared if you reload page so I don't see how you fixed anything with this.

**Comment by marcandre** [comment] 2015-02-19 15:43
@jbojcic1 
Let me provide an example of the best approach for single page app submitting forms via ajax:

```
$('form').parsley(); // Bind parsley first.
$('form').on('submit', function(evt) {
  // If we're here, it's because parsley's validation succeeded, otherwise the submit event is interrupted
  // here I make ajax post to save user
  evt.preventDefault(); // so the form isn't actually submitted
});
```

You can bind globally like `$(document).on('submit')` and not even have to worry about the order. This is the type of [technique used by Rails](https://github.com/rails/jquery-ujs/wiki/Unobtrusive-scripting-support-for-jQuery#data-remote-make-links-and-forms-submit-asynchronously-with-ajax) so that adding `data-remote=true` to any `<form>` will submit it via ajax instead of the classical way.

**Comment by AlexPiuPiu** [comment] 2016-03-24 02:30
hello everyone, I have the same problem about remote cache.
I have a solution. View source code,Make some small changes. like this:
` Parsley.addValidator('remote', {
        requirementType: {
            '': 'string',
            'validator': 'string',
            'reverse': 'boolean',
            'options': 'object'
        },

        validateString: function validateString(value, url, options, instance) {
        **  ##   url += "?date=" + new Date();**
            var data = {};
            var ajaxOptions;
            var csr;
            var validator = options.validator || (true === options.reverse ? 'reverse' : 'default');

            if ('undefined' === typeof Parsley.asyncValidators[validator]) throw new Error('Calling an undefined async validator: `' + validator + '`');

            url = Parsley.asyncValidators[validator].url || url;`

**Comment by marcandre** [comment] 2016-03-24 05:09
@AlexPiuPiu could you describe why you have a problem with the caching?

**Comment by AlexPiuPiu** [comment] 2016-03-25 07:11
@marcandre
my submit code like this:
        $('#addTreeDirectoryForm').parsley().on('form:submit', function () {
            // 清除缓存
            Parsley._remoteCache = {};  // clear cache
            .........
If you do not clear the cache, the next form submitted if the same field will appear problem.

**Comment by marcandre** [comment] 2016-03-26 02:23
@AlexPiuPiu We [already clear the cache on `form:submit`](https://github.com/guillaumepotier/Parsley.js/blob/master/src/parsley/remote.js#L99-L101), what you are doing has no effect.

**Comment by AlexPiuPiu** [comment] 2016-03-26 06:35
@marcandre 
Actually, when I was testing the '.parsley().on('form:submit')', I found that there was no clear cache.
I can't describe in great detail. 
‘Parsley._remoteCache = {}; ’,This code is absolutely useful.
