### ISSUE TITLE
parlsey refresh

### ISSUE THREAD

**Issue by 719media** [guillaumepotier/Parsley.js#1058] opened 2016-02-05 02:06 UTC
Hello

When an input is excluded according to parsley options, and then something is done (e.g. unhiding an element) that would normally include that element, it isn't added in. I would sort of expect this, given that re-evaluating conditions for all events in the form would be cumbersome, and probably not even work all that well.

However, the way around this I found was to call _refreshFields as seen in this jsfiddle (remove the commented line to have it work):

https://jsfiddle.net/whwm83za/22/

Given that this function isn't in the primary documentation, and also that it starts with an underscore, I wasn't sure if there is another way to do this. (A more standard refresh() method).

Thanks for your time!

**Comment by marcandre** [comment] 2016-02-05 16:07
Indeed, methods starting an `_` are private, best not use them and ask instead :smile:
Thanks for the fiddle.
Still not exactly sure what the issue is though. I mean, `_refreshFields` will be called whenever a form is validated, in particular if the user pressed `submit`. If you need (why?) that to happen earlier, you could call `isValid()` on the form, for example, does that work for you?

**Comment by 719media** [comment] 2016-02-05 18:15
Here I made the fiddle a little more clear.

https://jsfiddle.net/whwm83za/27/

**Comment by marcandre** [comment] 2016-02-06 00:27
I see. Because you're using `trigger = "input"`, you want it to start validating at once. As I wrote, you can call `isValid()` instead of `_refreshFields` and that should do it, or initialize (even when hidden/disabled) `$yourVisibleField.parsley()` should work too.

**Comment by marcandre** [comment] 2016-02-10 04:04
Closing, let me know if that doesn't resolve your issue.

**Closed by marcandre** 2016-02-10 04:04 UTC
