### ISSUE TITLE
How about an example of parsley form validation working with JavaScript?

### ISSUE THREAD

**Issue by DaveC426913** [guillaumepotier/Parsley.js#872] opened 2015-03-20 19:35 UTC
In your examples section I see a super-simple example of a form with no JavaScript. I find no examples of validation that will tie into my Angular.

My Save button will be disabled until the form is valid, so I need all those tie-ins.

And don't you guys believe in plunkers?

Am I looking in the wrong place??

**Comment by marcandre** [comment] 2015-03-21 02:23
Duplicate of #871

**Closed by marcandre** 2015-03-21 02:24 UTC
Labels: duplicate
