### ISSUE TITLE
multi select input type validation is not working. 

### ISSUE THREAD

**Issue by AnkitKundariya** [guillaumepotier/Parsley.js#1251] opened 2018-04-24 10:33 UTC
![image](https://user-images.githubusercontent.com/24821294/39181904-bd4616ae-47d8-11e8-89f2-4d77575a62c1.png)

> Uncaught Validator `undefined` does not handle multiple values validate

![image](https://user-images.githubusercontent.com/24821294/39182231-d52735cc-47d9-11e8-9579-e1577b162b15.png)
@guillaumepotier

**Comment by marcandre** [comment] 2018-04-24 11:51
Difficult to 
Hi!

My name is Marc-André and **I'd like to help**. I'm not the original author but I liked the project so much I started contributing more and more; now I'm the (only) maintainer.

#### How you can help

I'd like **you to help me** by doing everything you can on your end so I have to do less on my end. As you can imagine, I have already spent a lot of time making this project better, and given the price you're paying to use it or the efforts you have made contributing to this project, I think it's fair to ask that.

To serve that goal, I wrote that bug reports should **provide a working example** in the [READ ME](https://github.com/noelboss/featherlight#reporting-bugs-and-issues) file. Still, some people don't provide a working example here.

I requested the same in the [Contributing Guidelines](https://github.com/noelboss/featherlight/blob/master/.github/CONTRIBUTING.md). Even though GitHub has a paragraph saying "Please review the guidelines for contributing to this repository." that shows up whenever someone creates an issue, some people don't provide a working example.

Finally, GitHub allowed us to write a template issue, in which I wrote
> you must provide a minimal example in a CodePen
> starting from http://jsfiddle.net/JNsu6/15/.

Still, some people like you delete this text and report a bug without a working example. So I am wondering: **why did you feel it was the right thing to do**? What could I possibly have done so that this basic wish was respected? I must admit that I feel disrespected whenever someone completely ignores my requests. I understand that most developers don't feel the urge to help by digging in, inspecting the code and contributing back with great bug reports or pull requests, but it saddens me when people show little care and disregard maintainer wishes.

It would help me a lot if you helped me find a solution so that bug reports are posted with working examples.

#### Why Working Examples?

A working example is a great opportunity to minimize the problem, have the least amount of dependencies, etc.

Maybe by doing this, you will figure out what is going on. Or maybe the issue is something else than what you thought it was.

Or maybe the issue exists and this way, I can see it with a few clicks. If I only get partial code, I need to guess what the issue could be. Sometimes my understanding of the code is enough, I'll think about it and "ha ha", I know what the issue is. Usually I don't though, so then I have to copy-paste the bits and pieces given to me and try to reproduce the issue. This takes *me* some time that *you* could have spent.

So, if you have hints on how to avoid bug reports without working example, please let me know.

More to the point, provide a working example, for this project or any other where you can. I'm closing this and will reopen when there is a working example. Thank you for your understanding.

**Closed by marcandre** 2018-04-24 11:51 UTC
