### ISSUE TITLE
Parsley takes note of excluded fields on form submit, only

### ISSUE THREAD

**Issue by matths** [guillaumepotier/Parsley.js#1177] opened 2017-02-23 17:35 UTC
Parsley takes note of excluded fields on form submit, only,
but still validates fields that have `data-parsley-trigger="input keyup change"`.

This is very annoying, as I am looking now for hours for a solid way to exclude/include a field from validation with parsley.

I I've made this JSFiddle to illustrate the problem.
https://jsfiddle.net/Lwdppsvm/5/
Click the submit button, and  you will see only input[name=cafe] been validated (error).
Type something into input[name=bar] and see that it will not be excluded and still validated.

**Comment by marcandre** [comment] 2017-02-23 17:57
Thanks for the example.
I understand this can be annoying and should ideally be fixed.
In the meantime, you can call `$('#foo').parsley()._refreshFields()` to circumvent this.

**Comment by matths** [comment] 2017-02-23 19:15
I've made another example. '_refreshFields()' is also just good for the form submit.

I came up with the idea to use a dummy data-parsley-value to convince parsley to validate the field as ok.

https://jsfiddle.net/Lwdppsvm/6/

**Comment by marcandre** [comment] 2017-02-23 19:28
Oh, you're right, very sorry about this.
You've hit a very unfortunate series of bugs with the `excluded` option. This last one is easy to fix, let me push something that will help.

**Comment by marcandre** [comment] 2017-02-23 20:09
Ok, with the latest release, and calling `_refreshFields()`, I believe it works as expected. Here's the updated fiddle: https://jsfiddle.net/jkefx5z8/

PS: I lost a bunch of time looking at your fiddle until I realized they used a very version of Parsley... Always use the latest when filing bugs!

**Comment by keithort** [comment] 2017-02-27 21:25
I am experiencing a similar issue as described. I can't create a fiddle of the situation I'm running into but I'll explain as best I can. I am using Parsley 2.6.5 and jQuery 1.12.4. This is a simple multi-page information form storing data through the PHP Session and pre-populating fields through a JSON service.  When the user selects certain answers to questions (married, contact via email), new fields are made visible that are hidden via CSS. 

Here's a breaking scenario. A user marks themselves as either representing an individual or an entity. These are radio buttons and required fields. Depending on their selected input, new fields are made visible. When the related fields become visible, the `data-parsley-excluded` attribute flips from `true` to `false`. 

If the user clicks the button to continue on the form without selecting either individual or entity, Parsley marks the form as invalid and refuses to continue. This is the exact behavior required. Now If the user does choose one, say individual, that field is now valid and newly visible fields are set to be included for validation. When the user clicks the continuation button without populating the newly visible required fields, Parsley does not return an error and the user is allowed to continue. 

I have a function that toggles the `data-parsley-exclude` values and added `$('#theform').parsley()._refreshFields();` call at the end of it with no changes in behavior. 

Any guidance would be appreciated.

**Comment by marcandre** [comment] 2017-09-14 03:21
I'm not sure what you are describing is possible with Parsley, but maybe I'm not understanding correctly. Without a working fiddle, it's hard to tell.

I've added the method `refresh()` in 2.8.0. Parsley refreshes automatically before validating, but if you update the `excluded` option and want it to take effect now, you can call that.

Hopefully this addresses your issue, so I'm closing this. Otherwise, please provide a working example and I'll reopen :smile:

Thanks!

**Comment by MarcoSulla** [comment] 2019-03-24 12:24
The problem is still present:
https://jsfiddle.net/7kh4tvd8/1/
Please note it does not work neither on submit

**Comment by marcandre** [comment] 2019-03-25 04:44
Thanks for the fiddle @MarcoSulla 

Should be fixed in `master`.

**Comment by marcandre** [comment] 2019-03-25 05:04
Release as 2.8.2

**Closed by marcandre** 2019-03-25 05:04 UTC
