### ISSUE TITLE
Parsley.remote loading problem

### ISSUE THREAD

**Issue by alessandroliveri** [guillaumepotier/Parsley.js#985] opened 2015-09-23 15:18 UTC
Hi, 
I upgraded to the last version and I use parsley.remote instead parsley but when I load the script through requirejs I have an error 

<code>
Uncaught TypeError: Cannot read property 'on' 
</code>

caused by this code at line 2065 in parsley.remote.js

<code>
  window.Parsley.on('form:submit', function () {
    this._remoteCache = {};
  });
</code>

Any idea?

**Comment by marcandre** [comment] 2015-09-23 15:39
Are you loading just `parsley.remote` or both `parsley` and `parsley.remote`? It should be only the latter, but the instructions were misleading a while back...

**Comment by alessandroliveri** [comment] 2015-09-23 17:41
Only parsley.remote, this script seem include parsley

**Comment by marcandre** [comment] 2015-09-23 17:42
Which version are you using?

**Comment by alessandroliveri** [comment] 2015-09-23 17:45
2.1.3, I tried the both solutions (import only parsley.remote or parsley and parlsley.remote) same result

**Comment by marcandre** [comment] 2015-09-23 18:35
Ah ah!

That API is only for 2.2... Please check that out :smile:

**Comment by alessandroliveri** [comment] 2015-09-23 18:47
Is not the master version the 2.1.3 version? I installed it via bower, how I can use the stable version?

**Comment by marcandre** [comment] 2015-09-23 18:56
Well, 2.2 is still as a release candidate. Not too sure how to load it via bower, sorry.

**Comment by marcandre** [comment] 2015-09-23 18:56
Actually, I was wrong, `window.Parsley.on` should work in 2.1 anyways. Reopening

**Comment by marcandre** [comment] 2015-09-23 21:06
I can't figure out why you'd get that with 2.1.3.
Can you double check that's the result you get in the console with `window.Parsley.version`?

I made [a fiddle with that version](http://jsfiddle.net/zfmph5w6/) and the `remote` code loads fine.

**Comment by marcandre** [comment] 2015-09-23 21:09
The fiddle doesn't use `requirejs` though, so the problem has to be there... Sorry I can't easily help any further. If you could make a simple jsfiddle that would be great.

**Comment by alessandroliveri** [comment] 2015-09-24 07:05
http://jsfiddle.net/zfmph5w6/1/

As you can see in console the problem is with <code>window.Parsley</code>

**Comment by alessandroliveri** [comment] 2015-09-24 09:31
This problem occur only with the minified version

**Comment by SebT** [comment] 2015-10-15 16:52
Hi, 

I've installed parsley 2.1.3 via npm for browserify. I use `require('parsleyjs/dist/parsley.remote')` and I have the same error described in the original post.

I don't use the minified version and it still throws this error.

**Comment by khalwat** [comment] 2015-10-18 16:55
I can confirm this.  I have several sites that use Parsley (thank you!) with RequireJS.  Using the same code, if I use the `dist/parsley.min.js` loaded via RequireJS, it fails in mysterious ways.  Forms will simply not validate, with no console errors.

If I substitute in the `dist/parsley.js` version, everything works as expected.  For now, I've just uglified the `dist/parsley.js` and am using that successfully.  Something is amiss with the `dist/parsley.min.js` version with RequireJS.

**Comment by khalwat** [comment] 2015-10-18 17:12
I tried substituting in the latest 2.2.0-rc2 version of Parsley, but it exhibits the same problem.  Unfortunately, Parsley appears to be broke with RequireJS.

Unlike other posters in this thread, I'm not getting any errors.  Parsley just doesn't work, whether initialized via JS or via `data-parsley-validate`.

Again, loading Parsley via a plain old `<script>` tag works; loading it via RequireJS fails.

**Comment by marcandre** [comment] 2015-10-19 00:05
Sorry about this. We're very close of merging the `es6` branch into `master`, which will resolve this loading issue (and also remove the non-`remote` version)...

**Comment by khalwat** [comment] 2015-10-19 00:08
Thanks for the response.  I look forward to it, I'll check regularly for the merge.  In the meantime, my forms go on unvalidated :)

**Comment by khalwat** [comment] 2015-10-26 19:17
FWIW, I tried the ``es6`` branch to see if that'd work for me... but it's still having intermittent issues loading properly when loaded via RequireJS.

**Comment by marcandre** [comment] 2015-10-26 21:33
What issues exactly with the `es6` branch, @khalwat ?

**Comment by khalwat** [comment] 2015-10-29 15:17
@marcandre I may not have done it exactly right; I just replaced the `dist` folder from the release branch with the `dist` folder from the es6 branch.

The issues I had were very similar to what I was having with the release branch: 

When loaded with RequireJS, sometimes, ParsleyJS would not work for underdetermined reasons.  The symptoms are the Parsley won't validate blocks, and won't validate on form submission (it'll just hang).

In the same environment, if I load it via a `<script>` tag, it works properly.

I can give you a live staging URL to take a look at if it'll be helpful.  Should I be doing anything other than grabbing `parsley.min.js` from `dist` from the es6 branch?

**Comment by khalwat** [comment] 2015-11-03 20:30
@marcandre Let me know if there is anything I can do to assist you in tracking down this issue.

**Comment by marcandre** [comment] 2015-11-03 21:22
A live link would help for sure.

The `es6` branch landed in `master`, btw, so you can use the `2.2.0rc4` release.

Do you have an estimate at how often you get a problem?

**Comment by khalwat** [comment] 2015-11-03 22:56
@marcandre I updated to 2.2.0rc4 and it seems to be working!  Here is a live URL for you:

http://imawhale.com/apply

**Comment by marcandre** [comment] 2015-11-04 16:58
Cool. So I'm closing this, but if anybody runs into issues with the current version, let me know!

**Closed by marcandre** 2015-11-04 16:58 UTC

**Comment by jessemorton** [comment] 2016-01-15 14:50
I just installed it yesterday and have the issue as described at the top of @SebT's post trying to work with Parsley Remote.

**Comment by marcandre** [comment] 2016-01-15 16:56
@jessemorton Please upgrade to 2.2.0rc4

**Comment by jessemorton** [comment] 2016-01-15 18:34
Thanks for the speedy reply, @marcandre Maybe the NPM module just needs updating on your end? I installed via npm yesterday, but it looks like its v2.1.2. Doing `npm update parsleyjs` isn't accomplishing anything today.
